aptana/studio3

plugins/com.aptana.portal.ui/src/com/aptana/portal/ui/dispatch/actionControllers/AbstractActionController.java, plugins/com.aptana.portal.ui/src/com/aptana/portal/ui/dispatch/actionControllers/CommandHandlerActionController.java, plugins/com.aptana.samples.ui/src/com/aptana/samples/ui/handlers/ImportSampleHandler.java, plugins/com.aptana.samples.ui/src/com/aptana/samples/ui/portal/actionController/SamplesActionController.java, plugins/com.aptana.samples.ui/src/com/aptana/samples/ui/project/NewSampleProjectWizard.java, plugins/com.aptana.samples.ui/src/com/aptana/samples/ui/project/SampleProjectCreator.java
Changes that will allow to invoke the callback to the dashboard after the sample project is created.
=> TISTUD-7143 Support callbacks for calls from Studio dashboard

plugins/com.aptana.core/src/com/aptana/core/resources/ISocketMessagesHandler.java, plugins/com.aptana.ui/src/com/aptana/ui/dialogs/InputMessageDialog.java, plugins/com.aptana.ui/src/com/aptana/ui/dialogs/MultipleInputMessageDialog.java, plugins/com.aptana.ui/src/com/aptana/ui/handlers/AppcSocketMessagesHandler.java
Provides default handlers to prompt the user and get the responses for the requests from the underlying framework.
=> TISTUD-7113 TISTUD-7114 TISTUD-7223 TISTUD-7224  Integrate appc CLI with Studio

plugins/com.aptana.ui/src/com/aptana/ui/handlers/AppcSocketMessagesHandler.java
For the first time:
If user provided the wrong user name and password, CLI currently not returning error message, Will simply prompt a dialog with question. I will create a different CLI ticket for that.
=> TISTUD-7325:No validations on the login prompt shown within studio after

plugins/com.aptana.ui/src/com/aptana/ui/dialogs/MultipleInputMessageDialog.java
OK and Cancel labels are replaced with YES and NO labels
=> TISTUD-7408:Import: ACS - Improve UI in Prompting Dialog

plugins/com.aptana.git.core/src/com/aptana/git/core/model/GitRepository.java
Fix TISTUD-7467 NullPointerException for "update UI for index changes" after importing Movies sample
- Guard against null branches field (happens when repo has been "disposed").
=> Fix TISTUD-7467

plugins/com.aptana.ui/src/com/aptana/ui/dialogs/MultipleInputMessageDialog.java
the prompt text is chopped off at the bottom
=> TISTUD-7479:If you enable services on your Titanium app (non-platform),

plugins/com.aptana.ui/src/com/aptana/ui/dialogs/InputMessageDialog.java, plugins/com.aptana.ui/src/com/aptana/ui/dialogs/MultipleInputMessageDialog.java
Appc Studio should remember the last org you were logged in
=> TISTUD-7460:Appc Studio should remember the last org you were logged

plugins/com.aptana.samples.ui/src/com/aptana/samples/ui/portal/actionController/SamplesActionController.java, tests/com.aptana.samples.ui.tests/src/com/aptana/samples/ui/portal/actionController/SamplesActionControllerTest.java
Added mobile nature for dashboard projects as well.
=> TISTUD-7482:The four samples on Dashboard do not have option for

plugins/com.aptana.usage/src/com/aptana/usage/internal/DefaultAnalyticsEventHandler.java
=> TISTUD-7437:"Sending Analytics Ping" error when using a pre-4.0

plugins/com.aptana.formatter.epl/META-INF/MANIFEST.MF, plugins/com.aptana.formatter.epl/src/com/aptana/formatter/ScriptFormattingStrategy.java, plugins/com.aptana.formatter.epl/src/com/aptana/formatter/ui/FormatterMessages.java, plugins/com.aptana.formatter.epl/src/com/aptana/formatter/ui/FormatterMessages.properties, plugins/com.aptana.js.debug.core/src/com/aptana/js/debug/core/internal/model/JSDebugLineBreakpoint.java, plugins/com.aptana.js.debug.core/src/com/aptana/js/debug/core/model/JSDebugModel.java
-restoring the breakpoints after formatting
=> TISTUD-6655:Breakpoints disappear after formatting controller file

plugins/com.aptana.js.core/src/com/aptana/js/core/node/INodeJS.java, plugins/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodeJSService.java, tests/com.aptana.js.core.tests/src/com/aptana/js/internal/core/node/NodeJSTest.java
=> TISTUD-7756 : During the studio update check, verify minimum required

plugins/com.aptana.js.core/src/com/aptana/js/core/node/INodePackageManager.java, plugins/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodePackageManager.java, tests/com.aptana.js.core.tests/build.properties, tests/com.aptana.js.core.tests/resources/node_modules/appcelerator/package.json, tests/com.aptana.js.core.tests/src/com/aptana/js/internal/core/node/NodePackageManagerTest.java
Read the version from package.json file if the version is not returned from npm command.
Added tests.
=> TISTUD-7796 If you run "npm ls -g appcelerator" when a pre-release version is installed, "npm ERR! code 1" is returned

plugins/com.aptana.core/src/com/aptana/core/util/SudoProcessRunnable.java
iCloud Account is taking little bit more time to authenticate.
You can find the illustration below for timings:
Response with 3*50ms
```
p
pa
pas
pass
passw
passwo
passwor
password
Stream is not ready, attempt:0 sleepInterval:50
Stream is not ready, attempt:1 sleepInterval:50
Stream is not ready, attempt:2 sleepInterval:50
Stream is not ready even after: 150ms, hence exiting!
```
Response with 3*500ms
```
p
pa
pas
pass
passw
passwo
passwor
password
Stream is not ready, attempt:0 sleepInterval:500
Stream is not ready, attempt:1 sleepInterval:500
Stream is not ready, attempt:2 sleepInterval:500
password:
password:S
password:SU
password:SUC
password:SUCC
password:SUCCE
password:SUCCES
password:SUCCESS
```
=> TISTUD-7762 Studio unable to update if OSX (El Capitan) logon using

plugins/com.aptana.js.core/src/com/aptana/js/core/node/INodeJS.java, plugins/com.aptana.js.core/src/com/aptana/js/core/node/INodeJSService.java, plugins/com.aptana.js.core/src/com/aptana/js/core/node/INodePackageManager.java, plugins/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodeJS.java, plugins/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodeJSService.java, plugins/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodePackageManager.java
- During Studio startup, if Node.js version is lesser than the minimum required, then Studio will re-install Node.js
- It will then notify all its listeners to update the installed Node.js version
- Studio will then re-build the active appc core package, to re-compile the native bindings.
=> TISTUD-7804 Cannot open Studio after clean install

plugins/com.aptana.jira.core/src/com/aptana/jira/core/JiraManager.java, tests/com.aptana.jira.core.tests/src/com/aptana/jira/core/JiraManagerTest.java
* Studio will create AC projects
* Will verify whether the current studio version is there in the Appcelertor JIRA version list, if it's there, will set the affected version number, otherwise will set the affected version in the environment field.
* Added required test cases
=> TISTUD-7740 Unable to submit a JIRA ticket via Studio as "versions" is

plugins/com.aptana.jira.core/src/com/aptana/jira/core/JiraIssueSeverity.java
my bad, this is the one which spoiled my demo.
=> TISTUD-7879 JIRA ticket creation failing from studio if we select the

plugins/com.aptana.jira.core/src/com/aptana/jira/core/JiraIssueConfig.java, plugins/com.aptana.jira.core/src/com/aptana/jira/core/JiraManager.java, plugins/com.aptana.jira.ui/META-INF/MANIFEST.MF, plugins/com.aptana.jira.ui/src/com/aptana/jira/ui/handlers/SubmitTicketHandler.java, tests/com.aptana.jira.core.tests/src/com/aptana/jira/core/JiraManagerTest.java
=> TISTUD-7741 Add prominent display of "what you like/what can be better"

plugins/com.aptana.js.core/src/com/aptana/js/core/node/INodeJSService.java, plugins/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodeJSService.java
=> TISTUD-7756 During the studio update check, verify minimum required

plugins/com.aptana.jira.core/src/com/aptana/jira/core/JiraManager.java
=> TISTUD-7916 Can't login to Jira via Appcelerator Studio if login

plugins/com.aptana.samples.ui/plugin.xml
updated version as Classic
removed Samples view completely from Appcelerator studio
=> TISTUD-7602 Samples view lists out-dated Alloy RSS sample app and

plugins/com.aptana.ui/src/com/aptana/ui/dialogs/MultipleInputMessageDialog.java
=> TISTUD-8023 Don't allow to edit organization name in the Splash screen

plugins/com.aptana.editor.common/src/com/aptana/editor/common/CommonEditorPlugin.java, plugins/com.aptana.editor.common/src/com/aptana/editor/common/CommonUtil.java, plugins/com.aptana.editor.common/src/com/aptana/editor/common/preferences/EditorsPreferencePage.java
TISTUD-8466 - App designer in full screen mode - Showing Properties
and Elements on the left side
TISTUD-8487 - App Designer and App Preview not available for Indie
subscribers
=> TISTUD-8466 - App designer in full screen mode - Showing Properties and

plugins/com.aptana.git.ui/src/com/aptana/git/ui/internal/preferences/GithubAccountPageProvider.java, plugins/com.aptana.git.ui/src/com/aptana/git/ui/internal/preferences/Messages.java, plugins/com.aptana.git.ui/src/com/aptana/git/ui/internal/preferences/messages.properties
Note added use a personal token instead of password.
=> TISTUD-8477 Studio should support Github two factor authentication

plugins/com.aptana.portal.ui/src/com/aptana/portal/ui/internal/Portal.java
=> TISTUD-8561 Studio dashboard opening page blocks the user doing other

plugins/com.aptana.js.core/src/com/aptana/js/core/node/INodeJS.java, plugins/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodeJSService.java, tests/com.aptana.js.core.tests/src/com/aptana/js/internal/core/node/NodeJSTest.java
=> TISTUD-8553 Install: Install of version 4.8.0 fails due to node

plugins/com.aptana.core/src/com/aptana/core/resources/ISocketMessageHandlerListener.java, plugins/com.aptana.core/src/com/aptana/core/resources/ISocketMessagesHandler.java, plugins/com.aptana.core/src/com/aptana/core/resources/ISocketMessagesHandlerNotifier.java, plugins/com.aptana.core/src/com/aptana/core/resources/RequestCancelledException.java, plugins/com.aptana.core/src/com/aptana/core/resources/SocketMessagesHandler.java, plugins/com.aptana.ui/src/com/aptana/ui/handlers/AppcSocketMessagesHandler.java
=> TISTUD-7569 The studio login dialog after entering wrong credentials

plugins/com.aptana.usage/src/com/aptana/usage/AnalyticsEvent.java
As suggested by Kondal, introduced wait time while checking for IP Address.
=> TISTUD-8656 Studio freezes momentarily when opening or closing files

plugins/com.aptana.portal.ui/src/com/aptana/portal/ui/internal/Portal.java
TISTUD-8741 Studio dashboard shows "Server unavailable" page with CLI 6.2.0-master.62
Changing TSL protocol version to 1.2 as studio dashboard server is no longer accepting the requests from TSL1.0 version.
Due to this, while connecting to studio dashboard portal we are getting SSL handshake exception.
`javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake`
As of today, Appcelerator Studio uses JDK 1.7 and by default it will set the TSL protocol version to 1.0.
=> TISTUD-8741 Studio dashboard shows "Server unavailable" page with CLI

plugins/com.aptana.core/src/com/aptana/core/util/SudoManager.java
Converting sudo password required error status to info message
=> TISTUD-8762 Error reporting: sudo: a password is required

plugins/com.aptana.editor.xml/src/com/aptana/editor/xml/XMLEditor.java
From GB-536,
I’m in the XML view and I have a Label highlighted it would be nice if when I went go to the design view, that element was highlighted. Better yet the properties for that element showed in the properties window.
https://jira.appcelerator.org/browse/GB-542
https://github.com/appcelerator/titanium_studio/pull/934
https://github.com/aptana/studio3/pull/428
*Test Case:*
1. Open App designer editor
2. Drop some elements into the editor canvas
3. Switch to the XML view
4. Click on some element to get highlighted in the element tags - Single click or double click
5. Switch to the design view
6. The selected element in the XML editor will be highlighted in the designer canvas.
*Notes:*
1. This works only one way - i.e, XML view to Designer view
2. To get the selection in the XML …
=> GB-542 Highlight the selected element when switch between the design and

plugins/com.aptana.core/src/com/aptana/core/util/VersionUtil.java
Quick fix - but it will be for 4.11.0
=> TISTUD-8859 4.9.1 Studio crashes immediately

features/com.aptana.feature/feature.xml, plugins/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodeJSService.java
=> TISTUD-8947 Replace installer node.js 8.7 direct links with appcelerator

bundles/com.aptana.editor.html/src/com/aptana/editor/html/parsing/HTMLParser.java, bundles/com.aptana.formatter.epl/src/com/aptana/formatter/FormatterUtils.java, bundles/com.aptana.js.core/src/com/aptana/js/core/parsing/GraalASTWalker.java, bundles/com.aptana.js.core/src/com/aptana/js/core/parsing/GraalJSParser.java, bundles/com.aptana.js.core/src/com/aptana/js/core/parsing/ast/JSBinaryOperatorNode.java, bundles/com.aptana.js.core/src/com/aptana/js/internal/core/build/JSParserValidator.java, bundles/com.aptana.parsing/src/com/aptana/parsing/ast/ParseError.java, tests/com.aptana.editor.html.tests/src/com/aptana/editor/html/parsing/HTMLParserTest.java, tests/com.aptana.editor.html.tests/src/com/aptana/editor/html/validator/HTMLParseErrorValidatorTest.java, tests/com.aptana.js.core.tests/src/com/aptana/js/core/parsing/JSParserTest.java, tests/com.aptana.js.core.tests/src/com/aptana/js/internal/core/build/JSParserValidatorTest.java
This PR contains
- Showing the error on the correct line number in the js editor
- Fixing an issue with the JS comment folding when it's used in the HTML code
- Fixing a couple of test cases
=> TISTUD 9096 - Fixing ES6 issues

bundles/com.aptana.js.core/src/com/aptana/js/core/parsing/GraalASTWalker.java, tests/com.aptana.js.core.tests/src/com/aptana/js/core/parsing/JSParserTest.java
It will fix 14 test cases which related to switch cases and others
=> Fixing switch AST test cases

bundles/com.aptana.js.core/src/com/aptana/js/core/parsing/ast/JSStatementsNode.java, bundles/com.aptana.js.core/src/com/aptana/js/internal/core/build/JSStyleValidator.java, tests/com.aptana.js.core.tests/src/com/aptana/js/internal/core/build/JSStyleValidatorTest.java
It will almost fix 18 test cases
=> Fixing JSStyleValidator issues

bundles/com.aptana.js.core/src/com/aptana/js/core/parsing/GraalASTWalker.java
Fix the below test case from **JSParserTest**
```
@Test
public void testExtFiles() throws Exception
{
for (String file : ITestFiles.EXT_FILES)
{
parseFile(file);
assertNoErrors();
}
}
```
=> FIX: IllegalArgumentException("Invalid range given:..")

bundles/com.aptana.js.core/src/com/aptana/js/core/node/INodeJS.java, bundles/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodeJSService.java, tests/com.aptana.js.core.tests/src/com/aptana/js/internal/core/node/NodeJSTest.java
Related to TISTUD-9148, TISTUD-9115
=> fix: make Node.JS 10.13 the new minimum version, 10.17 the version we attempt to install

bundles/com.aptana.buildpath.core/src/com/aptana/core/build/UnifiedBuilder.java, bundles/com.aptana.core.io/plugin.xml, bundles/com.aptana.core.io/src/com/aptana/ide/core/io/internal/FileStoreAdapterFactory.java, bundles/com.aptana.index.core/src/com/aptana/index/core/IndexContainerJob.java, bundles/com.aptana.index.core/src/com/aptana/index/core/IndexUtil.java, bundles/com.aptana.scripting/build.properties, bundles/com.aptana.ui.io/src/com/aptana/ide/ui/io/Utils.java
https://jira.appcelerator.org/browse/TISTUD-9173
=> fix: ignore derived resources in builds/indexing
