plugins/com.aptana.js.core/src/com/aptana/js/core/node/INodePackageManager.java
plugins/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodePackageManager.java

1. Add method to uninstall a npm component from a working directory
2. Refactor  global prefix code and invoke it only for global installs

TISTUD-7114:Install npm components locally inside Studio application folder

---

plugins/com.aptana.theme/css/gtk_dark.css
plugins/com.aptana.theme/css/gtk_dashboard.css
plugins/com.aptana.theme/css/mac_dark.css
plugins/com.aptana.theme/css/mac_dashboard.css
plugins/com.aptana.theme/css/win_dark.css
plugins/com.aptana.theme/css/win_dashboard.css

Complete platform URI is required to identify the imported css file, hence reverting the change. Verified with eclipse 4.4 version.
If we only provide the name(example: @import url("dark.css");), then it's going and looking for a particular css file in the eclipse default themes folder i.e org.eclipse.themes/css folder
This reverts commit 0b870a9741dffb853a6184c818cef841b3fca58d.

Revert "TISTUD-7055 Toolbar: Border - A black border is appearing underneath the toolbar

---

plugins/com.aptana.js.core/src/com/aptana/js/core/node/INodePackageManager.java
plugins/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodePackageManager.java
plugins/com.aptana.projects/src/com/aptana/projects/wizards/AbstractProjectWizardContributor.java
plugins/com.aptana.projects/src/com/aptana/projects/wizards/IProjectWizardContributor.java
plugins/com.aptana.projects/src/com/aptana/projects/wizards/ProjectWizardContributionManager.java

Two supporting changes in order to facilitate the entire project creation workflow 
- NodePackageManager supports getting the module path of a package based on the specified requirements. Some of the required ones are : global and passing in the prefix path. For example, Alloy modules path will not be available from global anymore. The Alloy package module path can found only under ``~/.appcelerator/install/<version>/package`` as a local package.
- Creating a Mobile Project now supports contributors to provide the command line options. Previously, the contributors are just asked to do some action post project creation. Now, since we need to pass in additional flags such as --org-id and --no-services, the contributors should add additional command line flags.

TISTUD-6789 Studio should rely on CLI to register the app with 360 after project creation

---

plugins/com.aptana.samples.ui/src/com/aptana/samples/ui/project/NewSampleProjectWizard.java

- It will run the long import process in the wizard container, so that gives a nice process message.
- Associate the nature of the imported wizard, so that it can kick off the corresponding project completion handlers.

TISTUD-7354 Importing Samples into Appcelerator Studio is not changing guid or assigning org

---

plugins/com.aptana.core/src/com/aptana/core/util/EclipseUtil.java
tests/com.aptana.core.tests/src/com/aptana/core/util/EclipseUtilTest.java

Supporting changes for TISTUD-7318 Change the update stream based on the build identifier
- Add a method into EclipseUtil which can pull the branch that the build came off of (for RCP builds) by using a regexp against the aboutText.

Supporting changes for TISTUD-7318

---

plugins/com.aptana.ui/src/com/aptana/ui/dialogs/InputMessageDialog.java
plugins/com.aptana.ui/src/com/aptana/ui/dialogs/MultipleInputMessageDialog.java

While importing external projects by default studio is sending --no-services param, so services will not be enabled during the import.
When user click on on 'Enable Services' button from tiApp.xml editor, it will check whether it's required to replace ACS keys or not, If yes, user will be prompted with a confirmation dialog box and perform the appropriate action based on the user input.

TISTUD-7426:Handle ACS key replacement confirmation through studio

---

plugins/com.aptana.ui/plugin.xml

Let's not show samples view by default even in extended perspective

TISTUD-7526:Remove samples view

---

plugins/com.aptana.webserver.core/META-INF/MANIFEST.MF

After digging into this mobileweb launch issue, I found out Eclipse ships its customized plugin of apache.httpcomponents.httpcore and apache.httpcomponents.httpclient - which is a way trimmed version from the original apache plugins. Since those versions (4.3.1) are higher than our required (4.2.2), we end up loading a few of the classes from eclipse's apache classes. Then, we attempt to load the rest of classes from 4.2.2, we end up getting LinkageError due to mismatch of version numbers of same type. Tried to enforce both the min and max versions in manifest to make sure we only depend on our shipped apache, and trying to avoid loading the classes from Eclipse's shipped apache bundles.

TISTUD-7428 Studio launches Mobile Web in browser but returns "Connection Refused"

---

plugins/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodePackageManager.java

In some cases, node process is returning ERROR status even thought it could find package path. So with this will just enforce additional check

TISTUD-7641:Slow due to "Failed to get the node modules path for package

---

plugins/com.aptana.samples.ui/src/com/aptana/samples/ui/portal/actionController/SamplesActionController.java

null for sample Apple WatchOS2"
This needn't to be an error. will just consider as a warning.

TISTUD-8516 Avoid error notification for "Unable to retrieve the icon at

---

plugins/com.aptana.usage/src/com/aptana/usage/internal/AnalyticsLogger.java
plugins/com.aptana.usage/src/com/aptana/usage/internal/DefaultAnalyticsEventHandler.java
tests/com.aptana.usage.tests/src/com/aptana/usage/internal/DefaultAnalyticsEventHandlerTest.java

Due to some unknown reason, empty event files are getting generated. While studio parsing these event files it fails with NPE. - Let's avoid that!

TISTUD-8462 Sending Analytics Ping error

---

plugins/com.aptana.core/src/com/aptana/core/util/ProcessRunner.java

NPE is at :https://github.com/appcelerator/titanium_studio/blob/694eaa3db28ea34dc4d3138dc82a8748a9808c3e/plugins/com.appcelerator.titanium.core/src/com/appcelerator/titanium/core/internal/cli/NodeAppcCLI.java#L769
It was caused by InterruptedException at https://github.com/aptana/studio3/blob/61328452f22122753ebbed313cb5a14d9293e976/plugins/com.aptana.core/src/com/aptana/core/util/ProcessRunner.java#L403
so the solution is to, send the original status of the process execution so that callers will know the cause and handle them the way it's required - whether it's reporting to the user, log it or ignoring.

TISTUD-8703 Error reporting: NPE after launching the Studio

---

plugins/com.aptana.js.core/src/com/aptana/js/core/inferencing/JSTypeUtil.java

recorded for a return type
Converted to a warning message so that it won't report the user through error reporting pop-up. However, planning to implement the same mechanism throughout the studio.

TISTUD-8710 Error reporting: Null or Empty type name attempting to be

---

plugins/com.aptana.core/src/com/aptana/core/logging/IdeLog.java
plugins/com.aptana.git.core/src/com/aptana/git/core/GitRepositoryProviderType.java
plugins/com.aptana.git.core/src/com/aptana/git/core/model/GitRepository.java
plugins/com.aptana.js.core/src/com/aptana/js/core/inferencing/CommonJSResolver.java
tests/com.aptana.git.core.tests/src/com/aptana/git/core/GitCoreTests.java
tests/com.aptana.git.core.tests/src/com/aptana/git/core/GitRepositoryProviderTest.java

Commit#1: address the below issue
```
Exception:java.lang.NullPointerException: null
at com.aptana.core.util.StringUtil.join(StringUtil.java:406)
at com.aptana.core.util.StringUtil.join(StringUtil.java:311)
at com.aptana.js.core.inferencing.CommonJSResolver.getModuleId(CommonJSResolver.java:99)
at com.aptana.js.core.inferencing.JSNodeTypeInferrer.visit(JSNodeTypeInferrer.java:775)
at com.aptana.js.core.parsing.ast.JSInvokeNode.accept(JSInvokeNode.java:31)
at com.aptana.js.core.inferencing.JSNodeTypeInferrer.addTypes(JSNodeTypeInferrer.java:194)
at com.aptana.js.core.inferencing.JSNodeTypeInferrer.visit(JSNodeTypeInferrer.java:442)
at com.aptana.js.core.parsing.ast.JSConditionalNode.accept(JSConditionalNode.java:39)
at com.aptana.js.core.parsing.ast.JSTreeWalker.visit(JSTreeWalker.java:176) …
```

TISTUD-8847 NPE while importing studio dashboard project sample

---

plugins/com.aptana.portal.ui/src/com/aptana/portal/ui/dispatch/browserFunctions/DispatcherBrowserFunction.java

Ideally, we should control the MobileWeb option directly in the dashboard but this is same across the all the studio versions. Hence, making the changes in the studio3 repo so that if it's a MobileWeb we don't even notify the browser about its existence.

TISTUD-8899 Remove MobileWeb option from the Studio dashboard

---

plugins/com.aptana.js.core/src/com/aptana/js/core/node/INodeJS.java
plugins/com.aptana.js.core/src/com/aptana/js/internal/core/node/NodeJSService.java
tests/com.aptana.js.core.tests/src/com/aptana/js/internal/core/node/NodeJSTest.java

Adding 8.7 node.js temporary links
1. Updated the links with Node.js 8.7 - but these are having temporary links will replace the actual links during the GA time. Please refer https://jira.appcelerator.org/browse/TISTUD-8901
2. Update the minimum version required in the studio Installers to 7.6 - Windows and Mac
3. Update the minimum version required in the studio to 7.6
4. Install the node 8.7 if the minimum version criteria is not met while restarting the studio 5.0

TISTUD-8890 Install node.js 8.7 with the studio 5.0 installers

---

plugins/com.aptana.explorer/src/com/aptana/explorer/internal/ui/SingleProjectView.java

**Jira**: https://jira.appcelerator.org/browse/TISTUD-8984 
**Cause**: per eclipse documentation, recent versions of eclipse mandate that we return ITreeViewer object on any overridden getSelection() method of AbstractTreeViewer class.
Excerpt from doc - 
_Subclasses do not typically override this method, but implement getSelectionFromWidget(List) instead. If they override this method, they should return an ITreeSelection as well._
**Fix**: Removed old implementation of returning IStructuredSelection and returning ITreeSelection object on the project node.

Fix for TISTUD-8984: Eclipse-oxygen-2: Exceptions while creating Mobile Project in App Explorer view

---

bundles/com.aptana.editor.common/framework/ruble/editor.rb
bundles/com.aptana.editor.common/src/com/aptana/editor/common/AbstractThemeableEditor.java

The problem here is "we are unable to use protected java method in jruby since jdk9 with the JRuby 9.x" even if the super class method declared as "protected".
So far we are overriding the protected method by public method in the sub-class. But now that does't seem to work even. 
To overcome this issue, we have to make sure all the methods are which are getting invoked by JRuby should be public and accessible. 
This issue is similar to https://github.com/jruby/jruby/issues/4851

TISTUD-9075 Commenting out code with "command+ / " does not work

---

bundles/com.aptana.js.core/src/com/aptana/js/core/parsing/GraalJSParser.java
bundles/com.aptana.parsing/src/com/aptana/parsing/ast/ParseError.java
tests/com.aptana.editor.html.tests/src/com/aptana/editor/html/validator/HTMLParseErrorValidatorTest.java
tests/com.aptana.js.core.tests/src/com/aptana/js/core/parsing/GraalJSParserTest.java
tests/com.aptana.js.core.tests/src/com/aptana/js/core/parsing/JSParserTest.java
tests/com.aptana.js.core.tests/src/com/aptana/js/internal/core/build/JSParserValidatorTest.java

Removed the filename.js from the error marker.
Will include the error type in the error message which is either SyntaxError or ReferenceError.
**Example1:**
> 'string' = 2;
```
ReferenceError:1:1 Invalid left hand side for assignment\n" + 
"'string' = 2;\n" + 
" ^"
```
**Example2:**
> testing(
`SyntaxError:1:8 Expected an operand but found eof\n" + "testing(\n" + "        ^`

TISTUD 9099 - Incorrect filename shown in message on the error marker

---

bundles/com.aptana.index.core/src/com/aptana/internal/index/core/DiskIndex.java

1. This is to avoid huge amount of JS code dumping into the crash reports and hence increasing the crash file sizes
Example for the crash report
[crashreport_UTFDataformat.txt](https://github.com/aptana/studio3/files/2332007/crashreport_UTFDataformat.txt)

Let's not log the index file data

---

bundles/com.aptana.projects/src/com/aptana/projects/internal/wizards/Messages.java
bundles/com.aptana.projects/src/com/aptana/projects/internal/wizards/NewWebProjectWizard.java
bundles/com.aptana.projects/src/com/aptana/projects/internal/wizards/messages.properties
bundles/com.aptana.projects/src/com/aptana/projects/wizards/AbstractNewProjectWizard.java

Ref: https://jira.appcelerator.org/browse/TISTUD-7442 & https://jira.appcelerator.org/browse/CLI-1065
Introduced new enum to match Error codes returned by CLI (Ref CLI-1065)
Started adopting to the Error messages in various scenarios where Studio used to throw the user a question dialog (for credentials) each time there is a session expiry/invalidation.
Addressed multiple scenarios which make use of a user session.
Let us update this PR with all observations and suggestions to improve this further.

TISTUD-7442 : Refactoring Studio <-> CLI communication w.r.t. sessions

---

bundles/com.aptana.usage/src/com/aptana/usage/internal/SendPingJob.java

Let's not send the delete events for the closed project as it throws the exception while fetching the project description

TISTUD-9125 Deleting a closed project thrown an exception

---

bundles/com.aptana.core/src/com/aptana/core/ShellExecutable.java
bundles/com.aptana.core/src/com/aptana/core/util/ProcessRunner.java
bundles/com.aptana.core/src/com/aptana/core/util/ProcessUtil.java

On MacOS machines, when a native call to get 'env' are issued, it waits forever.
We needed a timeout here, as this may cause studio to be hung. 
Introducing a 10 second timeout in this particular case.

TISTUD-9107 : Introducing timeout for getEnvironment() call

---

bundles/com.aptana.editor.common/src/com/aptana/editor/common/text/AbstractFoldingComputer.java
bundles/com.aptana.editor.js/src/com/aptana/editor/js/contentassist/JSLocationIdentifier.java
bundles/com.aptana.js.core/src/com/aptana/js/core/parsing/GraalASTWalker.java
bundles/com.aptana.js.core/src/com/aptana/js/core/parsing/GraalJSParser.java
bundles/com.aptana.js.core/src/com/aptana/js/core/parsing/ThisAssignmentCollector.java
bundles/com.aptana.parsing/META-INF/MANIFEST.MF
bundles/com.oracle.js.parser/src/com/oracle/js/parser/AbstractParser.java
bundles/com.oracle.js.parser/src/com/oracle/js/parser/ParserContext.java
bundles/com.oracle.js.parser/src/com/oracle/js/parser/TokenStream.java
bundles/com.oracle.js.parser/src/com/oracle/js/parser/TokenType.java
tests/com.aptana.editor.html.tests/src/com/aptana/editor/html/validator/HTMLParseErrorValidatorTest.java
tests/com.aptana.editor.js.tests/src/com/aptana/editor/js/contentassist/JSContentAssistProposalTest.java

This will address almost 32 Test scenarios which are related to Content Assist and others.
This will bring down the overall failures from 91 to 59.
There is one case which is still failing on JSCA is:
com.aptana.editor.js.contentassist.JSContentAssistProposalTest.testObjectLiteral
which is bit tricky which I'll take after looking into other issues.

FIX: Addressing parser recovery and content proposal issues

---

bundles/com.oracle.js.parser/src/com/oracle/js/parser/Parser.java

This will avoid syntax errors in imported sample project
"hyperloop-examples" which is ES6 based
https://jira.appcelerator.org/browse/TISTUD-9145
Reference:
http://www.bradoncode.com/blog/2015/08/26/javascript-semi-colon-insertion/

TISTUD-9145 Semicolons are optional with import and export syntax

---

bundles/com.aptana.editor.common/src/com/aptana/editor/common/text/rules/CommentScanner.java
tests/com.aptana.editor.common.tests/src/com/aptana/editor/common/text/rules/CommentScannerTest.java

**JIRA**: https://jira.appcelerator.org/browse/TISTUD-9171
**Description**
Move from per-character scanning to bulk range scanning, which avoids locking the document for *every single characeter* in the range!
Long comment ranges would lead to pathological case where editors would just hang. (i.e. baked in sourcemaps triggered this)
Fixes TISTUD-9171

fix(editor): significantly improve performance scanning for task tags in comments in editors
